/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModaoRouteImport } from './routes/modao'
import { Route as ModaoPromocaoRouteImport } from './routes/modao-promocao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaoRoute = ModaoRouteImport.update({
  id: '/modao',
  path: '/modao',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaoPromocaoRoute = ModaoPromocaoRouteImport.update({
  id: '/modao-promocao',
  path: '/modao-promocao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modao': typeof ModaoRoute
  '/modao-promocao': typeof ModaoPromocaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modao': typeof ModaoRoute
  '/modao-promocao': typeof ModaoPromocaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modao': typeof ModaoRoute
  '/modao-promocao': typeof ModaoPromocaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modao' | '/modao-promocao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modao' | '/modao-promocao'
  id: '__root__' | '/' | '/modao' | '/modao-promocao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModaoRoute: typeof ModaoRoute
  ModaoPromocaoRoute: typeof ModaoPromocaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modao': {
      id: '/modao'
      path: '/modao'
      fullPath: '/modao'
      preLoaderRoute: typeof ModaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modao-promocao': {
      id: '/modao-promocao'
      path: '/modao-promocao'
      fullPath: '/modao-promocao'
      preLoaderRoute: typeof ModaoPromocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModaoRoute: ModaoRoute,
  ModaoPromocaoRoute: ModaoPromocaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
